### ISSUE TITLE
Payoff with no tour leads to division by zero error

### ISSUE THREAD

**Issue by dorthrithil** [Carbulator/carbulator-server#27]
```
Traceback (most recent call last):
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 101, in wrapper
    return fn(*args, **kwargs)
  File "/Users/fengelmann/.local/share/virtualenvs/car-sharing-app-server-YP9W_S34/lib/python3.6/site-packages/flask_restful/__init__.py", line 687, in wrapper
    resp = f(*args, **kwargs)
  File "/Users/fengelmann/developement/car-sharing-app-server/src/resources/payoff_resources.py", line 56, in post
    km_fraction_per_user[user_id] = km / total_km
ZeroDivisionError: division by zero
```

**Comment by dorthrithil** [comment]
Payoffs are not allowed now if there are not both tours and refuels
